// tslint:disable
/**
 * Conduit API
 * Conduit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GenericErrorModelErrors,
    GenericErrorModelErrorsFromJSON,
    GenericErrorModelErrorsToJSON,
} from './';

/**
 * 
 * @export
 * @interface GenericErrorModel
 */
export interface GenericErrorModel  {
    /**
     * 
     * @type {GenericErrorModelErrors}
     * @memberof GenericErrorModel
     */
    errors: GenericErrorModelErrors;
}

export function GenericErrorModelFromJSON(json: any): GenericErrorModel {
    return {
        'errors': GenericErrorModelErrorsFromJSON(json['errors']),
    };
}

export function GenericErrorModelToJSON(value?: GenericErrorModel): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'errors': GenericErrorModelErrorsToJSON(value.errors),
    };
}


