// tslint:disable
/**
 * Conduit API
 * Conduit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Article,
    ArticleFromJSON,
    ArticleToJSON,
} from './';

/**
 * 
 * @export
 * @interface MultipleArticlesResponse
 */
export interface MultipleArticlesResponse  {
    /**
     * 
     * @type {Array<Article>}
     * @memberof MultipleArticlesResponse
     */
    articles: Array<Article>;
    /**
     * 
     * @type {number}
     * @memberof MultipleArticlesResponse
     */
    articlesCount: number;
}

export function MultipleArticlesResponseFromJSON(json: any): MultipleArticlesResponse {
    return {
        'articles': (json['articles'] as Array<any>).map(ArticleFromJSON),
        'articlesCount': json['articlesCount'],
    };
}

export function MultipleArticlesResponseToJSON(value?: MultipleArticlesResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'articles': (value.articles as Array<any>).map(ArticleToJSON),
        'articlesCount': value.articlesCount,
    };
}


