// tslint:disable
/**
 * Conduit API
 * Conduit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Comment,
    CommentFromJSON,
    CommentToJSON,
} from './';

/**
 * 
 * @export
 * @interface MultipleCommentsResponse
 */
export interface MultipleCommentsResponse  {
    /**
     * 
     * @type {Array<Comment>}
     * @memberof MultipleCommentsResponse
     */
    comments: Array<Comment>;
}

export function MultipleCommentsResponseFromJSON(json: any): MultipleCommentsResponse {
    return {
        'comments': (json['comments'] as Array<any>).map(CommentFromJSON),
    };
}

export function MultipleCommentsResponseToJSON(value?: MultipleCommentsResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'comments': (value.comments as Array<any>).map(CommentToJSON),
    };
}


