// tslint:disable
/**
 * Conduit API
 * Conduit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NewArticle,
    NewArticleFromJSON,
    NewArticleToJSON,
} from './';

/**
 * 
 * @export
 * @interface NewArticleRequest
 */
export interface NewArticleRequest  {
    /**
     * 
     * @type {NewArticle}
     * @memberof NewArticleRequest
     */
    article: NewArticle;
}

export function NewArticleRequestFromJSON(json: any): NewArticleRequest {
    return {
        'article': NewArticleFromJSON(json['article']),
    };
}

export function NewArticleRequestToJSON(value?: NewArticleRequest): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'article': NewArticleToJSON(value.article),
    };
}


