// tslint:disable
/**
 * Conduit API
 * Conduit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewComment
 */
export interface NewComment  {
    /**
     * 
     * @type {string}
     * @memberof NewComment
     */
    body: string;
}

export function NewCommentFromJSON(json: any): NewComment {
    return {
        'body': json['body'],
    };
}

export function NewCommentToJSON(value?: NewComment): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'body': value.body,
    };
}


