// tslint:disable
/**
 * Conduit API
 * Conduit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NewUser,
    NewUserFromJSON,
    NewUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface NewUserRequest
 */
export interface NewUserRequest  {
    /**
     * 
     * @type {NewUser}
     * @memberof NewUserRequest
     */
    user: NewUser;
}

export function NewUserRequestFromJSON(json: any): NewUserRequest {
    return {
        'user': NewUserFromJSON(json['user']),
    };
}

export function NewUserRequestToJSON(value?: NewUserRequest): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'user': NewUserToJSON(value.user),
    };
}


