// tslint:disable
/**
 * Conduit API
 * Conduit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TagsResponse
 */
export interface TagsResponse  {
    /**
     * 
     * @type {Array<string>}
     * @memberof TagsResponse
     */
    tags: Array<string>;
}

export function TagsResponseFromJSON(json: any): TagsResponse {
    return {
        'tags': json['tags'],
    };
}

export function TagsResponseToJSON(value?: TagsResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'tags': value.tags,
    };
}


