// tslint:disable
/**
 * Conduit API
 * Conduit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUser
 */
export interface UpdateUser  {
    /**
     * 
     * @type {string}
     * @memberof UpdateUser
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUser
     */
    token?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUser
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUser
     */
    bio?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUser
     */
    image?: string;
}

export function UpdateUserFromJSON(json: any): UpdateUser {
    return {
        'email': !exists(json, 'email') ? undefined : json['email'],
        'token': !exists(json, 'token') ? undefined : json['token'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'bio': !exists(json, 'bio') ? undefined : json['bio'],
        'image': !exists(json, 'image') ? undefined : json['image'],
    };
}

export function UpdateUserToJSON(value?: UpdateUser): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'email': value.email,
        'token': value.token,
        'username': value.username,
        'bio': value.bio,
        'image': value.image,
    };
}


