// tslint:disable
/**
 * Conduit API
 * Conduit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    User,
    UserFromJSON,
    UserToJSON,
} from './';

/**
 * 
 * @export
 * @interface UserResponse
 */
export interface UserResponse  {
    /**
     * 
     * @type {User}
     * @memberof UserResponse
     */
    user: User;
}

export function UserResponseFromJSON(json: any): UserResponse {
    return {
        'user': UserFromJSON(json['user']),
    };
}

export function UserResponseToJSON(value?: UserResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'user': UserToJSON(value.user),
    };
}


